pipeline{
    agent any
    parameters {
        string(name: 'PERSON', defaultValue: 'GIDEON')
        choice(name: 'CHOICE', choices: ['R6', 'Death Stranding', 'Valorant', 'RD2'], description: 'Pick One Game')
    }
    stages{
        stage ('Plan phase'){
            steps{
                echo "Hi. This is ${params.PERSON} "
                echo "${params.PERSON} you have selected ${params.CHOICE}"
            }
        }
        stage ('code phase'){
            steps{
                echo 'Do you want to continue?'
            }
        }
        stage ('integrate phase'){
            when{
                not{
                    branch "master"
                }
            }
            steps {
                echo 'Integration test passed'
            }
        }
        stage ('testing phase'){
            parallel{
                stage ('unit test'){
                    steps{
                        echo 'running unit test'
                    }
                }
            }
        }
    }
}
